# Spark Omarchy theme for Alacritty
# Based on Sparkfabrik Design System

[colors.primary]
background = "#031527"  # Spark Black
foreground = "#FFFFFF"  # Spark White
dim_foreground = "#027ACA"  # Spark Light Blue
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#FFFFFF"
cursor = "#EB0000"  # Spark Red

[colors.vi_mode_cursor]
text = "#FFFFFF"
cursor = "#EB0000"

[colors.search.matches]
foreground = "#031527"
background = "#F7AD2C"  # Spark Yellow

[colors.search.focused_match]
foreground = "#FFFFFF"
background = "#EB0000"  # Spark Red

[colors.footer_bar]
foreground = "#FFFFFF"
background = "#0C335A"  # Spark Blue

[colors.hints.start]
foreground = "#031527"
background = "#F7AD2C"  # Spark Yellow

[colors.hints.end]
foreground = "#FFFFFF"
background = "#0C335A"

[colors.selection]
text = "#FFFFFF"
background = "#EB0000"  # Spark Red

[colors.normal]
black = "#031527"    # Spark Black
red = "#EB0000"      # Spark Red
green = "#008844"    # Spark Dark Green
yellow = "#F7AD2C"   # Spark Yellow
blue = "#027ACA"     # Spark Light Blue
magenta = "#8D1971"  # Spark Dark Purple
cyan = "#40C6CF"     # Spark Aquamarine
white = "#FFFFFF"    # Spark White

[colors.bright]
black = "#0C335A"    # Spark Blue
red = "#F36931"      # Spark Orange
green = "#68D366"    # Spark Lime
yellow = "#F7AD2C"   # Spark Yellow
blue = "#40C6CF"     # Spark Aquamarine
magenta = "#CD0089"  # Spark Purple
cyan = "#027ACA"     # Spark Light Blue
white = "#FFFFFF"    # Spark White

[colors.dim]
black = "#031527"
red = "#EB0000"
green = "#008844"
yellow = "#F7AD2C"
blue = "#027ACA"
magenta = "#8D1971"
cyan = "#40C6CF"
white = "#FFFFFF"

[[colors.indexed_colors]]
index = 16
color = "#F36931"  # Spark Orange

[[colors.indexed_colors]]
index = 17
color = "#CD0089"  # Spark Purple